version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 50M
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data/
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
