name: Documentation
on:
  push:
    branches:
      - main
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate documentation
        run: |
          pip install pdoc3
          pip install flask
          PYTHONPATH=src pdoc --html src/ --force --output-dir ./docs
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Documentation update
